# Site settings
title: MAP Tournament Handbook
description: Official wiki for the Mapping Appreciation Project Tournament
baseurl: "/map_tournament_wiki"
url: "https://sponnify.github.io"
logo: "/map_tournament_wiki/assets/images/map_logo.png"

# Theme settings
remote_theme: just-the-docs/just-the-docs
color_scheme: blue

# Search configuration
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  heading_level: 2
  # Maximum amount of previews per search result
  previews: 3
  # Maximum amount of words to display before/after a matched word
  preview_words_before: 5
  preview_words_after: 10
  # Set the search token separator
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  rel_url: true
  # Enable or disable the search button
  button: true
  # Restrict search to only tournament-info pages
  only: ["tournament-info"]

# Aux links for the upper right navigation
aux_links:
  "Main Sheet":
    - "https://docs.google.com/spreadsheets/d/1cZxY30bo03sssZXmq4SIC_s9QfgNa_mRfuE4T2xGrew/"
  "Discord":
    - "https://discord.gg/2vvAWrU9ZR"

# Collections
collections:
  tournament-info:
    output: true
    permalink: /map_tournament_wiki/tournament-info/:title/

# Default YAML values
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "tournament-info"
    values:
      layout: "page"

# Exclude from processing
exclude:
  - "*.config.js"
  - node_modules/
  - docker-compose.yml
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock

# Plugins
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

# Load GitHub-specific settings if the JEKYLL_ENV is "production"
jekyll_env: development

sass:
  sass_dir: _sass
  style: compressed