# Site settings
title: MAP Tournament Handbook
description: Official wiki for the Mapping Appreciation Project Tournament
baseurl: "/map_tournament_wiki"
url: "https://sponnify.github.io"
logo: "/map_tournament_wiki/assets/images/map_logo.png"

# Theme settings
remote_theme: just-the-docs/just-the-docs
color_scheme: blue

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "Main Sheet":
    - "//map-tournament-homepage.com"
  "Discord":
    - "https://discord.gg/2vvAWrU9ZR"

# Collections
collections:
  tournament-info:
    output: true
    permalink: /map_tournament_wiki/tournament-info/:title/

# Default YAML values
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "tournament-info"
    values:
      layout: "page"

# Exclude from processing
exclude:
  - "*.config.js"
  - node_modules/
  - docker-compose.yml
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock

# Plugins
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

# Load GitHub-specific settings if the JEKYLL_ENV is "production"
jekyll_env: development

sass:
  sass_dir: _sass
  style: compressed